name: Build wheels

on:
  push:
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "pp* *-win32" 
          # Added gcc to provide gfortran for SciPy 1.11.0 source builds
          CIBW_BEFORE_BUILD_MACOS: "brew install libomp gcc"
          CIBW_ENVIRONMENT_MACOS: >
            OpenMP_ROOT=$(brew --prefix libomp) 
            MACOSX_DEPLOYMENT_TARGET=11.0 
            FC=$(brew --prefix gcc)/bin/gfortran
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-listdeps {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}"
          CIBW_TEST_COMMAND: >
            pip install torch --index-url https://download.pytorch.org/whl/cpu &&
            python -c "import napypi; print(napypi.__version__)"
