name: Build wheels

on:
  push:
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-*"
          CIBW_SKIP: "pp* *-win32 *-manylinux_i686 *-musllinux_*"
          CIBW_TEST_SKIP: "*-manylinux*"

          PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu

          CIBW_BEFORE_BUILD_MACOS: "brew install libomp"
          CIBW_ENVIRONMENT_MACOS: >
            OpenMP_ROOT=$(brew --prefix libomp)
            MACOSX_DEPLOYMENT_TARGET=11.0

          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            delocate-listdeps {wheel} &&
            delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}

          CIBW_TEST_COMMAND: >
            python -c "import napypi; print(napypi.__version__)"

